### ISSUE TITLE
Error when requesting command format ( AT+CMD=? ) when command has more than 5 arguments.

### ISSUE THREAD

**Issue by andrewstillie** [marcinbor85/cAT#51]
Love this implementation, but I am experiencing an issue when requesting command format ( AT+CMD=? )with a command with 7 arguments.
Its there a limit on the max number of arguments a command can have or can I adjust this?

**Comment by andrewstillie** [comment]
I have fixed it by increasing the buf array size to 512

**static char buf[512];**

static struct cat_command_group cmd_group = {
        .cmd = cmds,
        .cmd_num = sizeof(cmds) / sizeof(cmds[0]),
};

static struct cat_command_group *cmd_desc[] = {
        &cmd_group
};

static struct cat_descriptor desc = {
        .cmd_group = cmd_desc,
        .cmd_group_num = sizeof(cmd_desc) / sizeof(cmd_desc[0]),

        .buf = buf,
        .buf_size = sizeof(buf)
};

**Comment by mdtopham** [comment]
Replace the 512 with a macro constant and identify it as such for configuration. Override it appropriately in your build process. 512 is an arbitrary limit that may need to be different on other platforms due to memory constraints.The original value was adequate for its intended purpose.#define CMD_BUFFER_SIZE 512 /* enough for 7 parameters */On Jan 9, 2024, at 8:20 AM, andrewstillie ***@***.***> wrote:﻿
I have fixed it by increasing the buf array size to 512
static char buf[512];
static struct cat_command_group cmd_group = {
.cmd = cmds,
.cmd_num = sizeof(cmds) / sizeof(cmds[0]),
};
static struct cat_command_group *cmd_desc[] = {
&cmd_group
};
static struct cat_descriptor desc = {
.cmd_group = cmd_desc,
.cmd_group_num = sizeof(cmd_desc) / sizeof(cmd_desc[0]),
    .buf = buf,
    .buf_size = sizeof(buf)

};
